apiVersion: v1
kind: Service
metadata:
  labels:
    service: udagram-reverseproxy-svc
  name: udagram-reverseproxy-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: udagram-reverseproxy
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
