script:
  - docker --version # print the version for logging
  - docker build -t udagram-api-user .
  - docker tag udagram-api-user hassantarek/udagram-api-user:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push hassantarek/udagram-api-user:v1
